LottieFiles/relottie

- .github/workflows/release.yml
> chore(github): gpr release

- .github/workflows/release.yml
> chore(github): fix gpr release & imp npm release

- .github/workflows/release.yml
> chore(github): fix npmrc GPR registry

- .github/workflows/release.yml
> chore(github): fixe gpr token

- .changeset/angry-ads-joke.md
- .changeset/late-wombats-rush.md
- .changeset/quick-olives-itch.md
- packages/last/src/index.ts
- packages/relottie-parse/src/parse.ts
- packages/relottie/package.json
> feat: minor parse, last & relottie improvements

- .github/workflows/release.yml
> chore(.github): split validate and release action

- .changeset/big-schools-divide.md
- .changeset/lovely-cycles-drop.md
- .changeset/tender-poems-double.md
- packages/last-builder/package.json
- packages/last/package.json
- packages/relottie-parse/package.json
- packages/relottie-stringify/package.json
- packages/relottie/package.json
> chore(package): fix export main & types

- .github/workflows/release.yml
- .size-limit.cjs
- package.json
- pnpm-lock.yaml
> ci: report bundle size 

- .changeset/fluffy-dolls-thank.md
- .changeset/grumpy-wasps-help.md
- .changeset/nervous-lemons-shout.md
- packages/relottie-parse/package.json
- packages/relottie-parse/src/options.ts
- packages/relottie-parse/src/parse.ts
- packages/relottie-parse/src/unified-relottie-parse.ts
- pnpm-lock.yaml
> feat(parse): remove deepMerge, improve dev deps, simplify options

- .changeset/big-tigers-dance.md
- .changeset/rude-dots-share.md
- packages/last/__tests__/__snapshots__/index.test.ts.snap
- packages/last/src/titles.ts
- packages/relottie-parse/src/entities.ts
> feat: assetFile title and node

- .changeset/rare-moles-try.md
- packages/last/__tests__/__snapshots__/index.test.ts.snap
- packages/last/src/titles.ts
- packages/relottie-parse/src/entities.ts
> fix(last, parse): remove referece-id duplicate

- .changeset/slimy-mayflies-brake.md
- packages/last/__tests__/__snapshots__/index.test.ts.snap
- packages/last/src/titles.ts
- packages/relottie-parse/src/entities.ts
> feat(last, parse): tp MatteParent title

- .changeset/five-crabs-talk.md
- .changeset/sixty-balloons-tap.md
- packages/last/__tests__/__snapshots__/index.test.ts.snap
- packages/last/src/titles.ts
- packages/relottie-parse/src/entities.ts
> fix: add collapseTransformNew & fix smoothness value

- .changeset/pink-berries-sniff.md
- packages/relottie-parse/playground.ts
- packages/relottie-parse/src/entities.ts
Reference: https://lottiefiles.github.io/lottie-docs/schema/#/$defs/text/text-document/properties/sw
> fix(parse): textDocument width (sw) node

- .changeset/lucky-needles-wink.md
- .changeset/many-mice-kiss.md
- .changeset/ninety-queens-compete.md
- .changeset/shaggy-islands-repair.md
- .changeset/tender-mirrors-cross.md
- packages/relottie-parse/playground.ts
- packages/relottie-parse/src/constants.ts
- packages/relottie-parse/src/index.ts
- packages/relottie-parse/src/options.ts
- packages/relottie-parse/src/parse.ts
- packages/relottie-parse/src/unified-relottie-parse.ts
- packages/relottie-stringify/src/index.ts
- packages/relottie-stringify/src/unified-relottie-stringify.ts
- packages/relottie/src/index.ts
> feat: improve parse options & file.message and fileData type namings and export

- .changeset/sixty-turkeys-relate.md
- packages/relottie-stringify/src/constants.ts
- packages/relottie-stringify/src/index.ts
> feat(stringify): export fileConstants

- .changeset/friendly-jars-know.md
- packages/relottie-cli/README.md
> docs: small readme change for test release

- .github/workflows/release.yml
> ci: improve release jobs

- package.json
- pnpm-lock.yaml
> chore(devDeps): bump monorepo clinic to 13.0.0

- .changeset/three-maps-deny.md
- packages/relottie-parse/src/entities.ts
> refactor(entities): remove duplicte objectEntity props

- .changeset/empty-ladybugs-crash.md
- packages/last/src/titles.ts
> fix(titles): mask-mode-none name

- .changeset/four-rockets-serve.md
- .changeset/plenty-onions-double.md
- packages/relottie-extract-features/__tests__/__snapshots__/features/karting.snap
- packages/relottie-extract-features/__tests__/__snapshots__/features/stroke.snap
- packages/relottie-extract-features/__tests__/__snapshots__/features/trim-path.snap
- packages/relottie-parse/__tests__/__snapshots__/features/stroke.snap
- packages/relottie-parse/__tests__/__snapshots__/features/trim-path.snap
- packages/relottie-parse/src/constants.ts
Adjusting values based on the lottie-docs changes https://github.com/LottieFiles/lottie-docs/pull/51 
since entity values are based on its schema.
> fix(parse/constants): trimMultipleShapesValues

- .changeset/polite-onions-smoke.md
- packages/last-builder/package.json
- packages/last/package.json
- packages/relottie-parse/package.json
- packages/relottie-stringify/package.json
- pnpm-lock.yaml
> chore: bump lottie-types version to v1.5.0

- packages/relottie-parse/README.md
Update the documentations for relottie-parse plugin
https://github.com/LottieFiles/relottie/tree/main/packages/relottie-stringify
> docs: correct import name for relottie-parse plugin

- .github/workflows/release.yml
> ci(release): update changeset gh token var

- README.md
- packages/last/README.md
- packages/relottie-extract-features/README.md
- packages/relottie-metadata/README.md
- packages/relottie-stringify/README.md
- packages/relottie/README.md
> docs(readme): minor improve links & stylings

- packages/last/README.md
> docs(last/readme): fix lac link

- README.md
- packages/relottie/README.md
> docs(readme): add relottie-metadata plugin & fix relottie-cli link

- .changeset/tough-knives-tease.md
- README.md
- packages/last-builder/package.json
- packages/last/package.json
- packages/relottie-extract-features/package.json
- packages/relottie-parse/package.json
- packages/relottie-parse/src/constants.ts
- packages/relottie-stringify/package.json
- pnpm-lock.yaml
Use LAC [lottie-types](https://github.com/lottie/lottie-types) that been moved from the [lottiefiles/lottie-types](https://www.npmjs.com/package/@lottiefiles/lottie-types)
> chore: use LAC lottie-types

- .changeset/sixty-moose-kick.md
- packages/relottie-extract-features/__tests__/__snapshots__/features/karting.snap
- packages/relottie-extract-features/__tests__/__snapshots__/features/slots-img.snap
- packages/relottie-extract-features/src/used-features.ts
> fix: properly check dilate static-value

- .changeset/brave-radios-laugh.md
- packages/relottie-extract-features/__tests__/__snapshots__/features/effects-blur.snap
- packages/relottie-extract-features/__tests__/__snapshots__/features/effects-fill.snap
- packages/relottie-extract-features/__tests__/__snapshots__/features/effects-matte3.snap
- packages/relottie-extract-features/__tests__/__snapshots__/features/effects-prolevels.snap
- packages/relottie-extract-features/__tests__/__snapshots__/features/effects-shadow.snap
- packages/relottie-extract-features/__tests__/__snapshots__/features/effects-stroke.snap
- packages/relottie-extract-features/__tests__/__snapshots__/features/effects-tint.snap
- packages/relottie-extract-features/__tests__/__snapshots__/features/effects-tritone.snap
- packages/relottie-extract-features/__tests__/__snapshots__/features/font-css.snap
- packages/relottie-extract-features/__tests__/__snapshots__/features/font-local.snap
- packages/relottie-extract-features/__tests__/__snapshots__/features/font-url.snap
- packages/relottie-extract-features/__tests__/__snapshots__/features/image-animated.snap
- packages/relottie-extract-features/__tests__/__snapshots__/features/image.snap
- packages/relottie-extract-features/__tests__/__snapshots__/features/karting.snap
- packages/relottie-extract-features/__tests__/__snapshots__/features/like.snap
- packages/relottie-extract-features/__tests__/__snapshots__/features/lock.snap
- packages/relottie-extract-features/__tests__/__snapshots__/features/slots-gradient-fill.snap
- packages/relottie-extract-features/__tests__/__snapshots__/features/slots-img.snap
- packages/relottie-extract-features/__tests__/__snapshots__/features/slots.snap
- packages/relottie-extract-features/__tests__/__snapshots__/features/switch.snap
- packages/relottie-extract-features/__tests__/__snapshots__/features/text.snap
- packages/relottie-extract-features/__tests__/__snapshots__/features/transform.snap
- packages/relottie-extract-features/src/used-features.ts
Some tools by default export Transform Skew with a static value 0
> fix(extract-features): properly check if Skew is being used

- .changeset/blue-ads-bow.md
- packages/last/src/titles.ts
> feat(titles): blend-mode-add & blend-mode-hard-mix

- .changeset/sharp-beans-boil.md
- .github/dependabot.yml
- .github/workflows/release.yml
- package.json
- packages/last-builder/package.json
- packages/last/package.json
- packages/relottie-cli/package.json
- packages/relottie-extract-features/package.json
- packages/relottie-metadata/package.json
- packages/relottie-parse/package.json
- packages/relottie/package.json
- pnpm-lock.yaml
- renovate.json
> chore: provenance, fix release, bump pnpm & rm renovate

- .github/workflows/release.yml
> chore(workflow): add PR permissions for releases

- .github/workflows/release.yml
> ci: better job names, run npm release after gpr & fix gh release

- .github/workflows/release.yml
> ci: remove default release option & no-git-tag flag for gpr

- .changeset/wicked-beds-own.md
- packages/relottie-extract-features/package.json
- packages/relottie-metadata/package.json
- pnpm-lock.yaml
> chore(metadata, extarct-features): fix monorepo deps version

- package.json
- pnpm-lock.yaml
> chore(pacakge): override old tar-fs inner deps

- package.json
- pnpm-lock.yaml
> chore(package): override old semver deps

- .changeset/sharp-avocados-film.md
- packages/relottie-extract-features/__tests__/__snapshots__/features/slots-img.snap
- packages/relottie-extract-features/src/used-features.ts
> feat: baselineShift feature checker
